#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxvid
Version  : 1.3.7
Release  : 1
URL      : https://downloads.xvid.com/downloads/xvidcore-1.3.7.tar.gz
Source0  : https://downloads.xvid.com/downloads/xvidcore-1.3.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0+
Requires: libxvid-lib = %{version}-%{release}
BuildRequires : nasm
BuildRequires : yasm

%description
1) Introduction
---------------
Xvid is a high performance and high quality MPEG-4 video de-/encoding
solution.

%package dev
Summary: dev components for the libxvid package.
Group: Development
Requires: libxvid-lib = %{version}-%{release}
Provides: libxvid-devel = %{version}-%{release}
Requires: libxvid = %{version}-%{release}

%description dev
dev components for the libxvid package.


%package lib
Summary: lib components for the libxvid package.
Group: Libraries

%description lib
lib components for the libxvid package.


%prep
%setup -q -n xvidcore
cd %{_builddir}/xvidcore

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586980874
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
pushd build/generic
%configure --disable-static
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1586980874
rm -rf %{buildroot}
pushd build/generic
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/xvid.h
/usr/lib64/libxvidcore.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxvidcore.so.4
/usr/lib64/libxvidcore.so.4.3
